services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agent_manager_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: agent_manager_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend/VKR
      dockerfile: Dockerfile
    container_name: agent_manager_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/VKR:/app:cached
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - backend

volumes:
  postgres_data: