services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agent_manager_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: agent_manager_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: agent_manager_frontend
    restart: unless-stopped
    ports:
      - "5173:5173" # Vite использует 5173
    volumes:
      - ./frontend:/app # Монтируем всю папку, чтобы код обновлялся в реальном времени
    command: npm run dev

# Define the named volume here
volumes:
  postgres_data: